// <auto-generated />
using Assignment_8_Mishra_Yeati.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_8_Mishra_Yeati.Migrations
{
    [DbContext(typeof(FinalProjectData))]
    partial class FinalProjectDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment_8_Mishra_Yeati.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("memberCommonFavColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfColorInSchoolLogo")
                        .HasColumnType("int");

                    b.Property<int>("peopleInTheTeam")
                        .HasColumnType("int");

                    b.Property<string>("schoolColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            memberCommonFavColor = "Yellow",
                            numberOfColorInSchoolLogo = 6,
                            peopleInTheTeam = 8,
                            schoolColor = "Blue"
                        },
                        new
                        {
                            Id = 2,
                            memberCommonFavColor = "Blue",
                            numberOfColorInSchoolLogo = 3,
                            peopleInTheTeam = 2,
                            schoolColor = "Red"
                        });
                });

            modelBuilder.Entity("Assignment_8_Mishra_Yeati.Models.Favoritebreakfastfoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("favBreakfastPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pancakeOrWaffle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOfDrink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOfEggsYouLike")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("breakfastFood");
                });

            modelBuilder.Entity("Assignment_8_Mishra_Yeati.Models.Hobby", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("favMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favPlaceToTravel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favSport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freeTimeActivity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hobbies");
                });

            modelBuilder.Entity("Assignment_8_Mishra_Yeati.Models.Info", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<string>("birthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("collegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("collegeYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("information");
                });
#pragma warning restore 612, 618
        }
    }
}
